// Baseline headers applied to every dynamic response from hooks.server.ts, success or error
// (see hooks.server.ts's outer try/catch, F11). COOP + COEP cross-origin-isolate the page, which
// Stockfish needs for SharedArrayBuffer / multi-threaded WASM (see docs/build-plan.md, "Key
// architecture calls"). static/_headers sets the same COOP/COEP (plus X-Frame-Options) for
// static assets, which never run through hooks.
//
// F10: Content-Security-Policy used to be set here as a static string, which didn't allow
// SvelteKit's own inline hydration bootstrap script to run (no nonce/hash was ever issued for
// it) -- CSP was blocking the app's own client startup. CSP is now generated by SvelteKit itself
// (`csp` in the kit config passed to the `sveltekit()` plugin in vite.config.ts), which stamps a
// nonce/hash onto both the header and the inline script it emits, so this file no longer sets
// Content-Security-Policy at all.
export const SECURITY_HEADERS: ReadonlyArray<readonly [string, string]> = [
	["Cross-Origin-Opener-Policy", "same-origin"],
	["Cross-Origin-Embedder-Policy", "require-corp"],
	["X-Content-Type-Options", "nosniff"],
	["Referrer-Policy", "strict-origin-when-cross-origin"],
];

export const applySecurityHeaders = (response: Response): Response => {
	for (const [name, value] of SECURITY_HEADERS) response.headers.set(name, value);
	return response;
};

// F09: auth responses must never be cached and must never leak a full URL (which could carry a
// token in its fragment, or simply reveal that sign-in activity happened) via the Referer header
// on a subsequent same-origin navigation. Applied in addition to (and stricter than) the general
// Referrer-Policy above, for every response under /auth/*.
export const applyAuthResponseHeaders = (response: Response): Response => {
	response.headers.set("Cache-Control", "no-store");
	response.headers.set("Referrer-Policy", "no-referrer");
	return response;
};
