// Bundled template library used when KV has no versioned library and
// `@game-coach/templates-chess` is not present in the workspace (it ships only a `seed/`
// folder today, not an importable package). Slots are restricted to the ones
// `slotValuesFromFacts` can always fill ("played", "swing", "best_move", "line") so this
// library never triggers the MissingSlotError fallback path itself.
import * as v from "valibot";
import { TemplateLibrarySchema, type TemplateLibrary } from "@game-coach/contracts/templates";

const raw = {
  version: 1,
  game: "chess",
  templates: [
    {
      id: "praise.any.strong_move",
      game: "chess",
      kind: "praise",
      errorClass: null,
      phase: "any",
      severities: [0],
      themeId: "piece_activity",
      description: "A strong or best move worth praising.",
      text: "Great move! {played} was one of the best options here.",
      slots: ["played"],
    },
    {
      id: "praise.any.good_find",
      game: "chess",
      kind: "praise",
      errorClass: null,
      phase: "any",
      severities: [0],
      themeId: "calculation",
      description: "A good, well-calculated move.",
      text: "Nice find with {played} - that keeps your position healthy.",
      slots: ["played"],
    },
    {
      id: "neutral.any.book_move",
      game: "chess",
      kind: "neutral",
      errorClass: null,
      phase: "any",
      severities: [0, 1],
      themeId: "opening_principles",
      description: "An ordinary, reasonable move with nothing to flag.",
      text: "{played} is a reasonable, quiet move. No action needed.",
      slots: ["played"],
    },
    {
      id: "neutral.any.keep_watching",
      game: "chess",
      kind: "neutral",
      errorClass: null,
      phase: "any",
      severities: [0, 1, 2, 3],
      themeId: "calculation",
      description: "Nothing urgent to say yet; the coach keeps watching.",
      text: "Noted. The engine liked {best_move} slightly more, but the position stays balanced.",
      slots: ["best_move"],
    },
    {
      id: "tactical_oversight.any.hanging_piece_generic",
      game: "chess",
      kind: "error",
      errorClass: "tactical_oversight",
      phase: "any",
      severities: [2, 3],
      themeId: "hanging_piece",
      // T1: this text already claims nothing beyond the move/best move/swing, so it stays
      // ungated (requiresEvidence defaults to false) even though its theme is a motif name.
      description: "Missed or allowed a concrete tactic such as a hung piece.",
      text: "After {played}, {best_move} was clearly stronger - you gave up about {swing} here.",
      slots: ["played", "best_move", "swing"],
    },
    // T1: a generic "any" template for every (error class x severity) this minimal fallback
    // bundle can be asked for, so the live judge (judge-facts-live.ts) is never left with
    // nothing to say for an error class this small library didn't otherwise cover. None of
    // these name a specific motif, so none need requiresEvidence.
    {
      id: "tactical_oversight.any.generic_inaccuracy",
      game: "chess",
      kind: "error",
      errorClass: "tactical_oversight",
      phase: "any",
      severities: [1],
      themeId: "calculation",
      description: "A small tactical slip with no single clear cause.",
      text: "{played} gives up a little ground here. {best_move} kept the position tighter.",
      slots: ["played", "best_move"],
    },
    {
      id: "positional.any.generic_error",
      game: "chess",
      kind: "error",
      errorClass: "positional",
      phase: "any",
      severities: [1, 2, 3],
      themeId: "piece_activity",
      description: "A positional slip: structure, placement or plan.",
      text: "{played} loosens your position a little. {best_move} kept things more solid.",
      slots: ["played", "best_move"],
    },
    {
      id: "endgame_technique.any.generic_inaccuracy",
      game: "chess",
      kind: "error",
      errorClass: "endgame_technique",
      phase: "any",
      severities: [1],
      themeId: "conversion",
      description: "A small technical slip in the ending cost a little ground.",
      text: "{played} gives up a little in this ending. {best_move} was the more precise choice.",
      slots: ["played", "best_move"],
    },
    {
      id: "endgame_technique.any.generic_mistake",
      game: "chess",
      kind: "error",
      errorClass: "endgame_technique",
      phase: "any",
      severities: [2],
      themeId: "conversion",
      description: "A technical error in the ending cost real ground.",
      text: "{played} costs you {swing} in this ending. {best_move} kept your technique on track.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "endgame_technique.any.generic_blunder",
      game: "chess",
      kind: "error",
      errorClass: "endgame_technique",
      phase: "any",
      severities: [3],
      themeId: "conversion",
      description: "A serious technical error in the ending cost real ground.",
      text: "{played} costs you {swing} in this ending. {best_move} was the move that kept everything under control.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "opening_prep.any.generic_inaccuracy",
      game: "chess",
      kind: "error",
      errorClass: "opening_prep",
      phase: "any",
      severities: [1],
      themeId: "opening_principles",
      description: "A small opening slip cost a little ground early on.",
      text: "{played} gives up a small amount of ground this early. {best_move} kept you closer to known theory.",
      slots: ["played", "best_move"],
    },
    {
      id: "opening_prep.any.generic_mistake",
      game: "chess",
      kind: "error",
      errorClass: "opening_prep",
      phase: "any",
      severities: [2],
      themeId: "opening_principles",
      description: "An opening error cost real ground early in the game.",
      text: "{played} costs you {swing} this early in the game. {best_move} was the steadier choice.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "opening_prep.any.generic_blunder",
      game: "chess",
      kind: "error",
      errorClass: "opening_prep",
      phase: "any",
      severities: [3],
      themeId: "opening_principles",
      description: "A serious opening error cost real ground early in the game.",
      text: "{played} costs you {swing} this early. {best_move} was the move that kept your position solid.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "time_pressure.any.generic_inaccuracy",
      game: "chess",
      kind: "error",
      errorClass: "time_pressure",
      phase: "any",
      severities: [1],
      themeId: "time_management",
      description: "A quick move cost a little ground with time to spare.",
      text: "{played} came out fast here. {best_move} was worth the extra seconds to find.",
      slots: ["played", "best_move"],
    },
    {
      id: "time_pressure.any.generic_mistake",
      game: "chess",
      kind: "error",
      errorClass: "time_pressure",
      phase: "any",
      severities: [2],
      themeId: "time_management",
      description: "A rushed move under the clock cost real ground.",
      text: "{played} cost you {swing} while rushed. {best_move} was available with a moment more thought.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "time_pressure.any.generic_blunder",
      game: "chess",
      kind: "error",
      errorClass: "time_pressure",
      phase: "any",
      severities: [3],
      themeId: "time_management",
      description: "A low clock led to a costly move.",
      text: "{played} cost you {swing} under real time pressure. {best_move} was the safer, shorter option.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "calculation_depth.any.generic_inaccuracy",
      game: "chess",
      kind: "error",
      errorClass: "calculation_depth",
      phase: "any",
      severities: [1],
      themeId: "calculation",
      description: "A short line was calculated one move too shallow.",
      text: "{played} stops the calculation a move early. {best_move} carried it one move further.",
      slots: ["played", "best_move"],
    },
    {
      id: "calculation_depth.any.generic_mistake",
      game: "chess",
      kind: "error",
      errorClass: "calculation_depth",
      phase: "any",
      severities: [2],
      themeId: "calculation",
      description: "A forcing line was miscalculated for real ground.",
      text: "{played} cost you {swing} in a line you had already started. {best_move} carried it to the actual point.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "calculation_depth.any.generic_blunder",
      game: "chess",
      kind: "error",
      errorClass: "calculation_depth",
      phase: "any",
      severities: [3],
      themeId: "calculation",
      description: "A deep line was miscalculated for a real loss.",
      text: "{played} cost you {swing} several moves into a line you had already started. {best_move} kept it under control.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "unclear.any.generic_inaccuracy",
      game: "chess",
      kind: "error",
      errorClass: "unclear",
      phase: "any",
      severities: [1],
      themeId: "defense",
      description: "A small loss happened for reasons that are not clear-cut.",
      text: "{played} loses a little ground here for no single clear reason. Worth a second look in review.",
      slots: ["played"],
    },
    {
      id: "unclear.any.generic_mistake",
      game: "chess",
      kind: "error",
      errorClass: "unclear",
      phase: "any",
      severities: [2],
      themeId: "defense",
      description: "An error does not fit a single clear pattern.",
      text: "{played} costs you {swing} without an obvious single cause. {best_move} was the more solid choice.",
      slots: ["played", "swing", "best_move"],
    },
    {
      id: "unclear.any.generic_blunder",
      game: "chess",
      kind: "error",
      errorClass: "unclear",
      phase: "any",
      severities: [3],
      themeId: "defense",
      description: "A real loss happened with no single obvious explanation.",
      text: "{played} gave up {swing} for reasons that do not reduce to one clean explanation. Worth a closer look after the game.",
      slots: ["played", "swing"],
    },
  ],
};

export const FALLBACK_TEMPLATE_LIBRARY: TemplateLibrary = v.parse(TemplateLibrarySchema, raw);
