// Parses every golden fixture (generated by `cargo test` from crates/chess-core/tests/golden.rs)
// against the packages/contracts valibot schemas that define ChessCoreApi's return shapes.
import * as v from "valibot";
import { describe, expect, it } from "vitest";
import {
  MoveFeaturesSchema,
  ParsedGameSchema,
  PlayedMoveSchema,
  UciInfoSchema,
} from "@game-coach/contracts/chess-core-api";

import moveFeaturesGolden from "../../golden/move_features.json" with { type: "json" };
import parsedGameGolden from "../../golden/parsed_game.json" with { type: "json" };
import playedMovesGolden from "../../golden/played_moves.json" with { type: "json" };
import uciInfosGolden from "../../golden/uci_infos.json" with { type: "json" };

describe("chess-core golden fixtures", () => {
  it("played_moves.json entries match PlayedMoveSchema", () => {
    const fixtures = playedMovesGolden as ReadonlyArray<{ id: string; playedMove: unknown }>;
    expect(fixtures.length).toBeGreaterThanOrEqual(12);
    for (const fixture of fixtures) {
      expect(() => v.parse(PlayedMoveSchema, fixture.playedMove), fixture.id).not.toThrow();
    }
  });

  it("move_features.json entries match MoveFeaturesSchema", () => {
    const fixtures = moveFeaturesGolden as ReadonlyArray<{ id: string; moveFeatures: unknown }>;
    expect(fixtures.length).toBeGreaterThanOrEqual(12);
    for (const fixture of fixtures) {
      expect(() => v.parse(MoveFeaturesSchema, fixture.moveFeatures), fixture.id).not.toThrow();
    }
  });

  it("uci_infos.json entries match UciInfoSchema or null", () => {
    const fixtures = uciInfosGolden as ReadonlyArray<{ id: string; uciInfo: unknown }>;
    expect(fixtures.length).toBeGreaterThan(0);
    const nullableUciInfo = v.nullable(UciInfoSchema);
    for (const fixture of fixtures) {
      expect(() => v.parse(nullableUciInfo, fixture.uciInfo), fixture.id).not.toThrow();
    }
  });

  it("parsed_game.json entries match ParsedGameSchema", () => {
    const fixtures = parsedGameGolden as ReadonlyArray<{ id: string; parsedGame: unknown }>;
    expect(fixtures.length).toBeGreaterThan(0);
    for (const fixture of fixtures) {
      expect(() => v.parse(ParsedGameSchema, fixture.parsedGame), fixture.id).not.toThrow();
    }
  });
});
